---
- name: package installation
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    
    - name: VHOST add
      become: true
      shell: |
         cat << EOF >> /etc/apache2/sites-available/projectname.conf
         ###### packagename
         <VirtualHost *:80>
         ServerName projectname.zodeak-dev.com
         DocumentRoot /var/www/html/service/projectname/projectname/client/dist/client
         <Directory /var/www/html/service/projectname/projectname/client/dist/client>
         
         </Proxy>
         </VirtualHost>
         EOF
         
      register: SEQOUT

    - debug: msg={{SEQOUT.stdout_lines}}
...
